# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on: workflow_dispatch

jobs:
  gradle-rc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - uses: gradle/gradle-build-action@v2
      id: setup-gradle
      with:
        gradle-version: 7.2
    - run: gradle build fatjar
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./releases/*.jar
        name: Downloadable Extension File
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        tag: "latest_build_by_github"
        body: "This jar file has been built by GitHub automatically.\nYou can view the latest version number in the [extension.properties](../../blob/main/src/main/resources/extension.properties) file."
        allowUpdates: true
        artifacts: "releases/*.jar"
